--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ChampOfGames/GroupsUI
build-by-default: true
branches:
- master
projects:
  GroupsUI:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3    
...
