--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ChampOfGames/GroupsUI
build-by-default: true
branches:
- master
projects:
  GroupsUI:
    path: "https://github.com/ChampOfGames/GroupsUI/blob/master/GroupsUI.png"
...
