name: GroupsUI
main: ChampOfGames\GroupsUI\Main
author: ChampOfGames
version: 1.0.0
api: 3.0.0
libs:
  format: virion
  vendor: raw
  src: https://poggit.pmmp.io/r/72870/FormAPI.phar
  
  
commands:
  groupsui:
    description: Manage Groups with an UI
    usage: /groupsui
